### PR TITLE
Test case for CommonJS only packages

### PR DESCRIPTION
**Pull request by cavellblood**
### Description
This demonstrates a fix for this issue https://github.com/nystudio107/craft/issues/64. The main fix is just the change to `vite.config.js` Every other change in this PR is just to demonstrate the fix.

### CODE REVIEW

**Comment by khalwat** [comment]
So it's just the leading slash that fixes it?

**Comment by khalwat** [comment]
Did you also need to change it here: https://github.com/nystudio107/craft/blob/craft-vite/cms/templates/_boilerplate/_partials/critical-css.twig#L12

```twig
{{ craft.vite.script("/src/js/app.ts", false) }}
```

?

**Comment by cavellblood** [comment]
This last change made everything work again with a fresh clone of my repo. My guess is that it worked before without this change because of some cache in `/node_modules/.vite`. But this code works after doing a `make build`.

**Comment by cavellblood** [comment]
So three files need a change:
1. `buildchain/vite.config.js`
2. `cms/config/vite.php`
3. `cms/templates/_boilerplate/_partials/critical-css.twig`

**Comment by khalwat** [comment]
Looks like the right way to do this is just change it to this in `buildchain/vite.config.js`:

```js
      input: {
        app: './src/js/app.ts',
      },
```

...then you don't need to change anything anywhere else, at least in my testing.

**Comment by cavellblood** [comment]
Ok. That looks good to me. Thanks.

You can close this if you've made those adjustments. Looks like there is a conflict now.

**Comment by khalwat** [comment]
I'm going to do a little more testing but you've been fantastic, thank you for digging into this!

**Pull request closed without merging**
